### ISSUE TITLE
Problem using pClean in R

### ISSUE THREAD

**Issue by AndreLuettig** [AimeeD90/pClean#1]
Hello,
I have some issues running the program in R with my dataset. The exact exception is the following one:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at Preprocessing.pCleanMainClass.doPreprocessing23(pCleanMainClass.java:366)
	at Preprocessing.pCleanMainClass.main(pCleanMainClass.java:61)

As it is related to the precursor not having any values in possibleCharges, I checked my mgf file to see, if any of the charge values are missing. All of the values have a value and it is one of the following strings: 2+, 1+, 3+. 4+. 5+.

My exact call for pClean was the one posted at the github website (pCleanGear(mgf=mgffile,outdir="jurkat/result",mem=2,cpu=0,mionFilter=TRUE,isoReduction=TRUE,chargeDeconv=TRUE,largerThanPrecursor=TRUE,ionsMerge=TRUE,network=TRUE)) with mgffile pointing to my mgf file, as described. 

Can you help me with that issue?

Best, 
André

**Comment by AndreLuettig** [comment]
Was my own fault, one of the entries did not have the CHARGE line
